name: CI/CD Pipeline

on:
  push:
    branches:
      - fathallah
  pull_request:
    branches:
      - fathallah

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for RabbitMQ
        run: |
          for i in {1..30}; do
            if docker exec rabbitmq rabbitmq-diagnostics -q ping; then
              break;
            fi;
            echo "Waiting for RabbitMQ to be ready...";
            sleep 2;
          done

      - name: Build with Maven
        run: mvn clean package

      - name: Run unit tests
        run: mvn test

      - name: Generate coverage report
        run: mvn jacoco:report

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_PRODUCT }} -Dsonar.organization=mspr-kawa-2024 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build . -t fathallahma/msprapiproduit:latest

      - name: Push Docker image
        run: docker push fathallahma/msprapiproduit:latest
